### Week 3 - Project : Segmenting and Clustering Neighborhoods in Toronto

In [1]:
import numpy as np
import pandas as pd
import requests

### Use the Notebook to build the code to scrape the following Wikipedia page, https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M, in order to obtain the data that is in the table of postal codes and to transform the data into a pandas dataframe

In [2]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
df_html = pd.read_html(requests.get(url).content, header = 0)[0]
df_html

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

### Only process the cells that have an assigned borough. Ignore cells with a borough that is Not assigned.

In [3]:
df_html = df_html[df_html.Neighbourhood != 'Not assigned']
df_html.reset_index(inplace = True)
df_html.head()

,index,Postal Code,Borough,Neighbourhood
0,2,M3A,North York,Parkwoods
1,3,M4A,North York,Victoria Village
2,4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,5,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,6,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"

### The dataframe will consist of three columns: PostalCode, Borough, and Neighborhood
#### PS: I have a dataframe copy to manipulate and rename dataframe

In [4]:
df = df_html.sort_values(by=['Neighbourhood'], ascending=False).groupby('Postal Code').agg(
               {
                   'Borough':'first',
                   'Neighbourhood': ', '.join
               }).copy()

df.reset_index(inplace = True)
df.rename(columns = {'Postal Code':'PostalCode','Neighbourhood':'Neighborhood' }, inplace = True)
df

    PostalCode      Borough                                       Neighborhood
0          M1B  Scarborough                                     Malvern, Rouge
1          M1C  Scarborough             Rouge Hill, Port Union, Highland Creek
2          M1E  Scarborough                  Guildwood, Morningside, West Hill
3          M1G  Scarborough                                             Woburn
4          M1H  Scarborough                                          Cedarbrae
..         ...          ...                                                ...
98         M9N         York                                             Weston
99         M9P    Etobicoke                                          Westmount
100        M9R    Etobicoke  Kingsview Village, St. Phillips, Martin Grove ...
101        M9V    Etobicoke  South Steeles, Silverstone, Humbergate, Jamest...
102        M9W    Etobicoke                Northwest, West Humber - Clairville

[103 rows x 3 columns]

### More than one neighborhood can exist in one postal code area. For example, in the table on the Wikipedia page, you will notice that M5A is listed twice and has two neighborhoods: Harbourfront and Regent Park. These two rows will be combined into one row with the neighborhoods separated with a comma as shown

In [5]:
df.loc[df['PostalCode'] == 'M5A']

   PostalCode           Borough               Neighborhood
53        M5A  Downtown Toronto  Regent Park, Harbourfront

### If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [6]:
df.loc[df['Neighborhood'] == 'Not assigned']

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

### If a cell has a borough but a Not assigned neighborhood, then the neighborhood will be the same as the borough.

In [7]:
df.loc[df['Borough'] == 'Not assigned']

Empty DataFrame
Columns: [PostalCode, Borough, Neighborhood]
Index: []

In [8]:
print(len(df['PostalCode'].unique()))

103

### In the last cell of your notebook, use the .shape method to print the number of rows of your dataframe

In [11]:
print(df.shape)

(103, 3)